language: php

php:
  - 7.1

before_script:
  - composer install
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate

script:
  - php vendor/bin/phpunit --debug

services:
  - postgresql
