language: php
sudo: false
php:
- 7.1
before_script:
- composer install
- psql -c 'create database travis_ci_test;' -U postgres
- cp .env.travis .env
- php artisan key:generate
- php artisan migrate
script:
- php vendor/bin/phpunit --debug
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: kM1FQRGigqBgk8hX7CIEHzHuydKSRrAxnmgmDKbGEHjQXEmr1bmaIFhX8JD/+taik+EEjK8nh39ikX5/oxUUKRs59qqNMhsgb4kWkEmWyXYThdYch84dBF6KjNOIVwSZ7kukYJMmIwLi9JXn+kpjp7zal43XqlAtR0HRtqVHRldFjZdDA7YBlDkMSfYSbFK/ZMmQ4tTXaqE+QK5/++0+Qv16fl66aBtDnzT+/zTFIqgrTJSNgf2nAfSxmWhhOGAnsPbO5wXicc+QHQ8PLTuW+KeexRXa5qo4KsXpBOUuVaA+z6epiuJZ8WGu3mq6Q+gf0zrGYYHrBUCze26BnTat1Sq6fFT1lqEEfLZ8B2r7eFETe5//QFEr+ENwFHI8rfHZ+5du8fI0wzEuf4iQup8qfYg0EEFZjB6Xfx/vgi0C+TEDnrTBmObxDRqdEFUEnn3kYY4wnppeqW+ZdllNInMJjFbjJseOzjXysYLMWHYprkFgwBW0UCBZx0RmJUl2+tp0hnVLhfSZSlm8FgJAJKFXfUnexpNk9op28LZ2/11dflZuwl6BakmvVdIAVTIeSaij6MY5N7Fk7JQ+QbpMC/SLpUIyWeG6ZVnn5nRzx1nhNOoaqhVfMsk3b5mysNc0mZi1syAslDw1ecGrnL1xI2t1kPd/ZULLvDMt8K6cLNQQIso=
