language: php
sudo: required
dist: trusty

php:
- 7.1

install:
  - travis_retry composer install --no-interaction

before_script:
- cp .env.example .env
- php artisan key:generate
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./vendor/laravel/dusk/bin/chromedriver-linux &
- php artisan serve &
- sleep 5

script:
- php artisan dusk
