language: php
sudo: required
dist: trusty

php:
- 7.1
install:
  - travis_retry composer install --no-interaction

before_script:

- psql -c 'create database travis_ci_test;' -U postgres
- cp .env.travis .env
- php artisan key:generate
- php artisan migrate
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./vendor/laravel/dusk/bin/chromedriver-linux &
- php artisan serve &

script:
- php vendor/bin/phpunit --debug
- php artisan dusk

services:
- postgresql
