language: php
sudo: false
php:
- 7.1
before_script:
- composer install
- psql -c 'create database travis_ci_test;' -U postgres
- cp .env.travis .env
- php artisan key:generate
- php artisan migrate
script:
- php vendor/bin/phpunit --debug
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: YOUR_KEY
  app:
    YOUR_APP_NAME
