language: php

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate
  - phantomjs --webdriver=127.0.0.1:9515 &
  - php artisan serve &
  - sleep 5

script:
  - php artisan dusk

services:
  - postgresql
